[package]
name = "my_rust_lab"
version = "0.1.0"
authors = ["sujoe <sujoe77@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
